### ISSUE TITLE
Porting to Pydroid

### ISSUE THREAD

**Issue by unclejohn56** [danislav/HeartRate#3]
Congratulations. This code works for Windows. 
I'm wondering, how hard it would be to port it to Pydroid (for Android)? 
What could be used in place of calls to msvcrt and pywinusb.hid?

**Comment by danislav** [comment]
Sorry for seeing this so late. Not sure why github didn't send a notification 😆 
For android - I would suggest just reading the usb hid data and port the code to an android application. I did it with python because was easy and ugly 😊

**Comment by unclejohn56** [comment]
Thanks for your reply. Easy and ugly is good for me :-) I've decided to stick with your code and enhance it a bit to work with multiple devices etc.
